# Generated by Django 5.1.7 on 2025-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carbrand/', verbose_name='Изображение на сайте'),
        ),
    ]
