# Generated by Django 5.1.7 on 2025-03-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year', 'model__brand__name', 'model__name'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ['name'], 'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['brand__name', 'name'], 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_volume',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN-номер'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='acceleration',
            field=models.DecimalField(blank=True, decimal_places=1, default=10.0, max_digits=3, null=True, verbose_name='Разгон до 100 км/ч (сек)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'Внедорожник'), ('crossover', 'Кроссовер'), ('wagon', 'Универсал'), ('pickup', 'Пикап'), ('minivan', 'Минивэн'), ('coupe', 'Купе'), ('convertible', 'Кабриолет')], default='sedan', max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='clearance',
            field=models.PositiveIntegerField(blank=True, default=160, null=True, verbose_name='Дорожный просвет (мм)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, default=1.6, max_digits=3, verbose_name='Объем двигателя (л)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_consumption',
            field=models.DecimalField(blank=True, decimal_places=1, default=7.5, max_digits=3, null=True, verbose_name='Расход топлива (л/100км)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], default='petrol', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=1500, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/', verbose_name='Основное изображение'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная модель'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=4500, null=True, verbose_name='Длина (мм)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='max_speed',
            field=models.PositiveIntegerField(blank=True, default=180, null=True, verbose_name='Максимальная скорость (км/ч)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='power',
            field=models.PositiveIntegerField(default=100, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механическая'), ('automatic', 'Автоматическая'), ('robot', 'Робот'), ('variator', 'Вариатор')], default='manual', max_length=20, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='trunk_volume',
            field=models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Объем багажника (л)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='wheelbase',
            field=models.PositiveIntegerField(blank=True, default=2600, null=True, verbose_name='Колесная база (мм)'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=1800, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комплектации')),
                ('equipment_type', models.CharField(choices=[('standard', 'Стандарт'), ('comfort', 'Комфорт'), ('luxury', 'Люкс'), ('premium', 'Премиум'), ('sport', 'Спорт')], max_length=20, verbose_name='Тип комплектации')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='autosalon.carmodel', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='autosalon.equipment', verbose_name='Комплектация'),
        ),
        migrations.CreateModel(
            name='EquipmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название функции')),
                ('category', models.CharField(choices=[('safety', 'Безопасность'), ('comfort', 'Комфорт'), ('multimedia', 'Мультимедиа'), ('exterior', 'Экстерьер'), ('interior', 'Интерьер'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='autosalon.equipment', verbose_name='Комплектация')),
            ],
            options={
                'verbose_name': 'Функция комплектации',
                'verbose_name_plural': 'Функции комплектаций',
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='model_images/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='autosalon.carmodel', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Изображение модели',
                'verbose_name_plural': 'Изображения моделей',
            },
        ),
    ]
