# Generated by Django 5.1.7 on 2025-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0004_alter_car_options_alter_carbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='has_climate_control',
            field=models.BooleanField(default=True, verbose_name='Климат-контроль'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='has_heated_steering_wheel',
            field=models.BooleanField(default=True, verbose_name='Подогрев руля'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='multimedia_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Мультимедийная система'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='seat_heating',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подогрев сидений'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='trunk_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем багажника (л)'),
        ),
    ]
